---
format_version: '11'
default_step_lib_source: https://github.com/bitrise-io/bitrise-steplib.git
project_type: flutter

pipelines:
  primary:
    stages:
    - analyze-and-test-stage: { }
    - export-stage: { }
stages:
  analyze-and-test-stage:
    abort_on_fail: true
    workflows:
    - analyze: { }
    - test: { }
  export-stage:
    abort_on_fail: true
    workflows:
    - export-ios-app: { }
    - export-android-apk: { }

workflows:
  _setup:
    steps:
    - git-clone: { }
    - restore-dart-cache: { }
    - flutter-installer:
        inputs:
        - is_update: false
  _teardown:
    steps:
    - save-dart-cache: { }
  analyze:
    before_run:
      - _setup
    after_run:
      - _teardown
    steps:
    - flutter-analyze: { }
    - deploy-to-bitrise-io: { }
  test:
    before_run:
      - _setup
    after_run:
      - _teardown
    description: |
      Runs tests.
    steps:
    - flutter-test: { }
    - deploy-to-bitrise-io: { }
  export-ios-app:
    before_run:
      - _setup
    after_run:
      - _teardown
    steps:
    - flutter-build:
        inputs:
        - platform: ios
        - ios_additional_params: --simulator
        - ios_output_pattern: |-
            *build/ios/iphonesimulator/*.app
    - deploy-to-bitrise-io: { }
  export-android-apk:
    before_run:
      - _setup
    after_run:
      - _teardown
    steps:
    - flutter-build:
        inputs:
        - platform: android
        - android_additional_params: --debug
    - deploy-to-bitrise-io: { }

meta:
  bitrise.io:
    stack: osx-xcode-14.2.x-ventura
    machine_type_id: g2.8core
