---
format_version: '11'
default_step_lib_source: https://github.com/bitrise-io/bitrise-steplib.git
project_type: flutter

trigger_map:
- pull_request_source_branch: "*"
  pipeline: primary

pipelines:
  primary:
    stages:
    - analyze-and-test: { }
    - deploy-debug: { }
  deploy:
    stages:
    - analyze-and-test: { }
    - deploy-release: { }

stages:
  analyze-and-test:
    abort_on_fail: true
    workflows:
    - analyze: { }
    - test: { }
  deploy-debug:
    abort_on_fail: true
    workflows:
    - export-ios-debug-app: { }
    - export-android-debug-apk: { }
  deploy-release:
    abort_on_fail: true
    workflows:
    - export-ios-release-ipa: { }
    - export-android-release-apk: { }

workflows:
  _setup:
    steps:
    - git-clone@8: { }
    - restore-dart-cache@1: { }
    - flutter-installer@0:
        inputs:
        - is_update: false
  _save_cache:
    steps:
    - save-dart-cache@1: { }
  analyze:
    before_run:
    - _setup
    steps:
    - flutter-analyze@0: { }
    - deploy-to-bitrise-io@2: { }
  test:
    before_run:
    - _setup
    description: |-
      Runs tests.
    steps:
    - flutter-test@1: { }
    - deploy-to-bitrise-io@2: { }
  export-ios-debug-app:
    before_run:
    - _setup
    steps:
    - flutter-build@0:
        inputs:
        - platform: ios
        - ios_additional_params: --simulator
        - ios_output_pattern: |-
            *build/ios/iphonesimulator/*.app
    - deploy-to-bitrise-io@2: { }
  export-android-debug-apk:
    before_run:
    - _setup
    after_run:
    - _save_cache
    steps:
    - flutter-build@0:
        inputs:
        - platform: android
        - android_additional_params: --debug
    - deploy-to-bitrise-io@2: { }
    meta:
      bitrise.io:
        stack: linux-docker-android-20.04
  export-ios-release-ipa:
    before_run:
    - _setup
    steps:
    - certificate-and-profile-installer@1: { }
    - flutter-build@0:
        inputs:
        - platform: ios
        - ios_output_type: archive
        - ios_output_pattern: |-
            *build/ios/ipa/*.ipa
    - deploy-to-bitrise-io@2: { }
    - deploy-to-itunesconnect-deliver@2: { }
  export-android-release-apk:
    before_run:
    - _setup
    after_run:
    - _save_cache
    steps:
    - flutter-build@0:
        inputs:
        - platform: android
        - android_additional_params: --release --split-per-abi
    - deploy-to-bitrise-io@2: { }
    - google-play-deploy@3: { }
    meta:
      bitrise.io:
        stack: linux-docker-android-20.04
